drop table if exists lito.line_items;
create table if not exists lito.line_items (
	id varchar(64) primary key,
	order_id varchar(64),
	created_at timestamp,
	created_at_est timestamp,
	_sku varchar(128),
	name varchar(128), 
	price numeric(26,2), 
	quantity numeric(26,2), 
	title varchar(128), 
	variant_title varchar(128), 
	total_discount numeric(26,2), 
	fulfillable_quantity numeric(26,2), 
	fulfillment_status varchar(64), 
	gift_card varchar(64), 
	grams numeric(26,2), 
	product_exists varchar(64), 
	product_id varchar(64), 
	_inventory varchar(64), 
	requires_shipping varchar(64), 
	sku varchar(128), 
	tax_lines varchar(1024), 
	taxable varchar(64), 
	variant_id varchar(64),
	variant_inventory_management varchar(64), 
	vendor varchar(64),
	estimated_ship_date varchar(64),
	_inventory_source varchar(64),
	order_test varchar(64),
	order_total_tax varchar(64),
	order_financial_status varchar(64),
	order_cancelled_at varchar(64),
	order_discount_amount varchar(64),
	order_country varchar(64),
	order_state varchar(64),
	order_city varchar(128),
	order_zip_code varchar(64),
	customer_email varchar(128),
	customer_first_name varchar(128),
	customer_last_name varchar(128),	
	orders_count varchar(64))
;
